# Generated by Django 3.2.8 on 2021-11-05 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AK',
            fields=[
                ('selftext', models.TextField(blank=True, null=True)),
                ('fullsize', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.SlugField(max_length=350)),
                ('author', models.CharField(max_length=50)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AP',
            fields=[
                ('selftext', models.TextField(blank=True, null=True)),
                ('fullsize', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.SlugField(max_length=350)),
                ('author', models.CharField(max_length=50)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.SlugField(max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='APComment',
            fields=[
                ('author', models.CharField(max_length=50)),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='children', to='archives.apcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='archives.ap')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AKComment',
            fields=[
                ('author', models.CharField(max_length=50)),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='children', to='archives.akcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='archives.ak')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
