# Generated by Django 3.2.8 on 2021-11-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('content_type', 'object_id')},
        ),
    ]
