# Generated by Django 3.2.9 on 2021-12-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_report_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ap',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
