# Generated by Django 3.2.9 on 2021-12-09 21:53

from django.db import migrations
from helpers.helpers import metadata as m

def add_metadata(apps, schema_editor):
    models = apps.get_models('archives')
    archives = list(filter(lambda x: x._meta.model_name in ['ap','ak'], models))
    for archive in archives:
        for object in archive.objects.all():
            object.json = m(object, pp=True)
            object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20211209_2151'),
    ]

    operations = [
        migrations.RunPython(add_metadata),
    ]
