# Generated by Django 3.2.9 on 2021-12-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20211209_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='nsfw',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='akcomment',
            name='awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ap',
            name='nsfw',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apcomment',
            name='awards',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
