# Generated by Django 3.2.9 on 2021-12-27 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20211225_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='PF',
            fields=[
                ('nsfw', models.BooleanField(blank=True, null=True)),
                ('selftext', models.TextField(blank=True, null=True)),
                ('fullsize', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.SlugField(max_length=350)),
                ('author', models.CharField(max_length=50)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PornFree Posts',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFW',
            fields=[
                ('nsfw', models.BooleanField(blank=True, null=True)),
                ('selftext', models.TextField(blank=True, null=True)),
                ('fullsize', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.SlugField(max_length=350)),
                ('author', models.CharField(max_length=50)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PornFreeWomen Posts',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PHW',
            fields=[
                ('nsfw', models.BooleanField(blank=True, null=True)),
                ('selftext', models.TextField(blank=True, null=True)),
                ('fullsize', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.SlugField(max_length=350)),
                ('author', models.CharField(max_length=50)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.DateTimeField()),
                ('score', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'PornHatesWomen Posts',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ak',
            options={'ordering': ['-id'], 'verbose_name_plural': 'AntiKink Posts'},
        ),
        migrations.AlterModelOptions(
            name='akcomment',
            options={'verbose_name_plural': 'AntiKink Comments'},
        ),
        migrations.AlterModelOptions(
            name='ap',
            options={'ordering': ['-id'], 'verbose_name_plural': 'AntiPornography Posts'},
        ),
        migrations.AlterModelOptions(
            name='apcomment',
            options={'verbose_name_plural': 'AntiPornography Comments'},
        ),
        migrations.CreateModel(
            name='PHWComment',
            fields=[
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=50)),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='children', to='archives.phwcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='archives.phw')),
            ],
            options={
                'verbose_name_plural': 'PornHatesWomen Comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFWComment',
            fields=[
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=50)),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='children', to='archives.pfwcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='archives.pfw')),
            ],
            options={
                'verbose_name_plural': 'PornFreeWomen Comments',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PFComment',
            fields=[
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=50)),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='children', to='archives.pfcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='archives.pf')),
            ],
            options={
                'verbose_name_plural': 'PornFree Comments',
                'abstract': False,
            },
        ),
    ]
