# Generated by Django 3.2.9 on 2021-12-31 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0006_auto_20211227_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ak',
            options={'ordering': ['-id'], 'verbose_name': 'AntiKink Post', 'verbose_name_plural': 'AntiKink Posts'},
        ),
        migrations.AlterModelOptions(
            name='akcomment',
            options={'verbose_name': 'AntiKink Comment', 'verbose_name_plural': 'AntiKink Comments'},
        ),
        migrations.AlterModelOptions(
            name='ap',
            options={'ordering': ['-id'], 'verbose_name': 'AntiPornography Post', 'verbose_name_plural': 'AntiPornography Posts'},
        ),
        migrations.AlterModelOptions(
            name='apcomment',
            options={'verbose_name': 'AntiPornography Comment', 'verbose_name_plural': 'AntiPornography Comments'},
        ),
        migrations.AlterModelOptions(
            name='pf',
            options={'ordering': ['-id'], 'verbose_name': 'PornFree Post', 'verbose_name_plural': 'PornFree Posts'},
        ),
        migrations.AlterModelOptions(
            name='pfcomment',
            options={'verbose_name': 'PornFree Comment', 'verbose_name_plural': 'PornFree Comments'},
        ),
        migrations.AlterModelOptions(
            name='pfw',
            options={'ordering': ['-id'], 'verbose_name': 'PornFreeWomen Post', 'verbose_name_plural': 'PornFreeWomen Posts'},
        ),
        migrations.AlterModelOptions(
            name='pfwcomment',
            options={'verbose_name': 'PornFreeWomen Comment', 'verbose_name_plural': 'PornFreeWomen Comments'},
        ),
        migrations.AlterModelOptions(
            name='phw',
            options={'ordering': ['-id'], 'verbose_name': 'PornHatesWomen Post', 'verbose_name_plural': 'PornHatesWomen Posts'},
        ),
        migrations.AlterModelOptions(
            name='phwcomment',
            options={'verbose_name': 'PornHatesWomen Comment', 'verbose_name_plural': 'PornHatesWomen Comments'},
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(default=79, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ak',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='ap',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='pf',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='pfw',
            name='title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='phw',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
