# Generated by Django 3.2.9 on 2021-12-31 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_auto_20211231_0110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
