# Generated by Django 3.2.9 on 2022-01-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_auto_20220105_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIM',
            fields=[
                ('nsfw', models.BooleanField(blank=True, null=True)),
                ('selftext', models.TextField(blank=True, null=True)),
                ('fullsize', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('flair', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=1, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('json', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PornIsMisogyny Post',
                'verbose_name_plural': 'PornIsMisogyny Posts',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PIMComment',
            fields=[
                ('awards', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(max_length=50)),
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('bgcolor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='children', to='archives.pimcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='archives.pim')),
            ],
            options={
                'verbose_name': 'PornIsMisogyny Comment',
                'verbose_name_plural': 'PornIsMisogyny Comments',
                'abstract': False,
            },
        ),
    ]
