# Generated by Django 3.2.9 on 2022-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_pim_pimcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='status',
            field=models.CharField(choices=[(1, 'Published'), (2, 'Unpublished'), (3, 'Reported')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='ap',
            name='status',
            field=models.CharField(choices=[(1, 'Published'), (2, 'Unpublished'), (3, 'Reported')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='pf',
            name='status',
            field=models.CharField(choices=[(1, 'Published'), (2, 'Unpublished'), (3, 'Reported')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='pfw',
            name='status',
            field=models.CharField(choices=[(1, 'Published'), (2, 'Unpublished'), (3, 'Reported')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='phw',
            name='status',
            field=models.CharField(choices=[(1, 'Published'), (2, 'Unpublished'), (3, 'Reported')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='pim',
            name='status',
            field=models.CharField(choices=[(1, 'Published'), (2, 'Unpublished'), (3, 'Reported')], default=1, max_length=2),
        ),
    ]
