# Generated by Django 3.0.1 on 2021-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_upload_images',
            field=models.BooleanField(default=True),
        ),
    ]
